// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	business "layered-architecture/model"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IPersonService is an autogenerated mock type for the IPersonService type
type IPersonService struct {
	mock.Mock
}

// GetAllPersons provides a mock function with given fields:
func (_m *IPersonService) GetAllPersons() []*business.Person {
	ret := _m.Called()

	var r0 []*business.Person
	if rf, ok := ret.Get(0).(func() []*business.Person); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*business.Person)
		}
	}

	return r0
}

// NewIPersonService creates a new instance of IPersonService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPersonService(t testing.TB) *IPersonService {
	mock := &IPersonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
